table Category_Summary
	lineageTag: c670bd02-cd7b-48e8-b251-09df2b72c96a

	column SubCategoryClass
		dataType: string
		lineageTag: 34c4b888-ea3b-4693-ba56-4fe3ae2e8297
		summarizeBy: none
		sourceColumn: SubCategoryClass

		annotation SummarizationSetBy = Automatic

	column Total_Sales_Count
		dataType: int64
		formatString: 0
		lineageTag: f16d4ee0-7306-4c0e-b088-a48711d5b626
		summarizeBy: none
		sourceColumn: Total_Sales_Count

		annotation SummarizationSetBy = Automatic

	column Total_Units_Sold
		dataType: int64
		formatString: 0
		lineageTag: 8eef8892-93c7-40fa-981d-9dad35c328cb
		summarizeBy: none
		sourceColumn: Total_Units_Sold

		annotation SummarizationSetBy = Automatic

	column Total_Revenue
		dataType: double
		lineageTag: dae1131a-6ca4-4199-bbeb-f396abf0e511
		summarizeBy: sum
		sourceColumn: Total_Revenue

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Discount
		dataType: double
		lineageTag: aa10e4ce-84e4-4ccf-ba7c-4ab9df439f61
		summarizeBy: sum
		sourceColumn: Total_Discount

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Units Per Transaction'
		dataType: double
		lineageTag: d3918392-3bb8-455c-9658-d949c7fdd819
		summarizeBy: none
		sourceColumn: Units Per Transaction

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Avg_Revenue_Per_Unit
		dataType: double
		lineageTag: a767ac5a-fbf2-4f01-9f5e-44a96e397a1d
		summarizeBy: average
		sourceColumn: Avg_Revenue_Per_Unit

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount_Rate_%
		dataType: double
		formatString: %0.00;-%0.00;%0.00
		lineageTag: 7fef1ea9-104b-4367-8137-396719f7e3a2
		summarizeBy: average
		sourceColumn: Discount_Rate_%

		annotation SummarizationSetBy = User

	column Total_Returns
		dataType: int64
		formatString: 0
		lineageTag: 851d664b-c235-43e8-960c-f2df1d13ace6
		summarizeBy: sum
		sourceColumn: Total_Returns

		annotation SummarizationSetBy = User

	column Return_Rate_%
		dataType: double
		formatString: %0.00;-%0.00;%0.00
		lineageTag: 70d0ef18-f5b9-4ce8-80a5-6ddd2fcf9b09
		summarizeBy: average
		sourceColumn: Return_Rate_%

		annotation SummarizationSetBy = User

	column Total_ChangeCard
		dataType: int64
		formatString: 0
		lineageTag: 13793bbe-96e8-4daf-b39f-fca69005e022
		summarizeBy: sum
		sourceColumn: Total_ChangeCard

		annotation SummarizationSetBy = User

	column Total_ChangeCard_Percentage
		dataType: double
		lineageTag: e2c7aeb6-2197-49ab-9ea3-67aa008ebab9
		summarizeBy: average
		sourceColumn: Total_ChangeCard_Percentage

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Category_Summary = m
		mode: import
		source =
				let
				  Kaynak = Excel.Workbook(Web.Contents("https://stdyildizedu-my.sharepoint.com/personal/denis_sokmener_std_yildiz_edu_tr/Documents/Uygulamalar/Microsoft Power Query/Uploaded Files/mavi_powerbi_export.xlsx"), null, true),
				  #"Gezinti 1" = Kaynak{[Item = "Category_Summary", Kind = "Sheet"]}[Data],
				  #"Yükseltilen üst bilgiler" = Table.PromoteHeaders(#"Gezinti 1", [PromoteAllScalars = true]),
				  #"Değiştirilen sütun türü" = Table.TransformColumnTypes(#"Yükseltilen üst bilgiler", {{"SubCategoryClass", type text}, {"Total_Sales_Count", Int64.Type}, {"Total_Units_Sold", Int64.Type}, {"Total_Revenue", type number}, {"Total_Discount", type number}, {"Units Per Transaction", type number}, {"Avg_Revenue_Per_Unit", type number}, {"Discount_Rate_%", type number}, {"Total_Returns", Int64.Type}, {"Return_Rate_%", type number}, {"Total_ChangeCard", Int64.Type}, {"Total_ChangeCard_Percentage", type number}}, "tr")
				in
				  #"Değiştirilen sütun türü"

	annotation PBI_ResultType = Table

